### ISSUE TITLE
missing characters in subscripts

### ISSUE THREAD

**Issue by AlexisRenchon** [ypsu/latex-to-unicode#9]
Is it intended? 
there's 28 lines in https://github.com/ypsu/latex-to-unicode/blob/master/data/subscripts, a lot of letters are missing

**Comment by ypsu** [comment]
I simply didn't find all the characters back then. You can see that in https://en.wikipedia.org/wiki/Superscripts_and_Subscripts_(Unicode_block) a lot of characters are missing. Having said that, I now went through all the forks and stolen all the additions people added. Commit f08d44b7 in particular should now extend this. If you find the rest, let me know, or better, send me a patch. Thanks! :)
